name: Scheduled GET Request

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  request_job:
    runs-on: ubuntu-latest
    steps:
      - name: Make GET request
        run: curl -X GET "https://ai-academy.onrender.com"
